using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

public static class UnityConstantsGenerator
{
    private const string OutputPath = "Assets/Scripts/Generated/UnityConstants.cs";

    [MenuItem("Tools/Generate Unity Constants")]
    public static void Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by UnityConstantsGenerator. Do not edit manually.");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();

        GenerateTags(sb);
        GenerateLayers(sb);
        GenerateSortingLayers(sb);
        GenerateScenes(sb);

        var dir = Path.GetDirectoryName(OutputPath);
        if (!Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(OutputPath, sb.ToString());
        AssetDatabase.Refresh();
        Debug.Log($"Unity constants generated at {OutputPath}");
    }

    private static void GenerateTags(StringBuilder sb)
    {
        sb.AppendLine("public static class Tags");
        sb.AppendLine("{");
        foreach (var tag in UnityEditorInternal.InternalEditorUtility.tags)
        {
            sb.AppendLine($"    public const string {Sanitize(tag)} = \"{tag}\";");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateLayers(StringBuilder sb)
    {
        sb.AppendLine("public static class Layers");
        sb.AppendLine("{");
        for (var i = 0; i < 32; i++)
        {
            var name = LayerMask.LayerToName(i);
            if (string.IsNullOrEmpty(name)) continue;
            sb.AppendLine($"    public const int {Sanitize(name)} = {i};");
        }
        sb.AppendLine();
        sb.AppendLine("    public static int GetMask(params string[] layerNames) => LayerMask.GetMask(layerNames);");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateSortingLayers(StringBuilder sb)
    {
        sb.AppendLine("public static class SortingLayers");
        sb.AppendLine("{");
        foreach (var layer in SortingLayer.layers)
        {
            sb.AppendLine($"    public const int {Sanitize(layer.name)} = {layer.id};");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateScenes(StringBuilder sb)
    {
        sb.AppendLine("public static class Scenes");
        sb.AppendLine("{");
        foreach (var scene in EditorBuildSettings.scenes)
        {
            if (!scene.enabled) continue;
            var sceneName = Path.GetFileNameWithoutExtension(scene.path);
            sb.AppendLine($"    public const string {Sanitize(sceneName)} = \"{sceneName}\";");
        }
        sb.AppendLine("}");
    }

    private static string Sanitize(string name)
    {
        var result = Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
        if (char.IsDigit(result[0]))
            result = "_" + result;
        return result;
    }
}